spring:
  datasource:
    url: jdbc:mysql://192.168.59.103:3306/security?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  session:
    store-type: none
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    encoding: utf-8
    cache: false
muke:
  security:
    social:
      qq:
        app-id: 101571214
        app-secret: 12a65a30751ae7a08dba7b31efa530d6
        providerId: callback
      filterProcessesUrl: /qq/login
server:
  port: 9000